sudo: false
language: python

python:
- '2.7'

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

addons:
  apt:
    packages:
    - pandoc
    - lacheck
    - php5
    - php5-cli

install:
- curl -sS https://getcomposer.org/installer | php
- php composer.phar require seld/jsonlint

script: make test

notifications:
  slack:
    secure: Z+1KSBeIhFfra53JrWE5eS6PupdOyrtVZ5g5aMw99WSxCnFzKDDsj669kLxm2dq5c/HYSxE0sc9mFaabDn+urusR0J3vKdac7nQdJIBRPdroqIAxQFAnnn+Y6r0OUqIQuLWqVNfDwr4JPdck9jI1n8X4Rg7MVsRlSoyfXDqK/LU=
