sudo: required
dist: trusty
language: python

python:
 - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install pandoc lacheck
  - composer self-update
  - composer global require seld/jsonlint

script: make test

notifications:
  irc: "irc.freenode.org#oparl"
