sudo: required
dist: trusty
language: python

python:
 - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc lacheck php5
  - curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

install:
  - composer global require seld/jsonlint

before_script:
  - export PATH=$PATH:"~/.composer/vendor/bin"

script: make test

notifications:
  irc: "irc.freenode.org#oparl"
